// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYG5nG6lOPqzMlZkaRZgW2JJnER7CAsE',
    appId: '1:22686388340:web:e89ab509f0a3a680170121',
    messagingSenderId: '22686388340',
    projectId: 'zen-challenge',
    authDomain: 'zen-challenge.firebaseapp.com',
    storageBucket: 'zen-challenge.firebasestorage.app',
    measurementId: 'G-24DQKQXXRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIafS8lcMaUwgDmFncdmQqPHXp6BRYIwE',
    appId: '1:22686388340:android:faa6b0f5916bf95c170121',
    messagingSenderId: '22686388340',
    projectId: 'zen-challenge',
    storageBucket: 'zen-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7HalGzA4vOUMHziaEACivubhToAIc74',
    appId: '1:22686388340:ios:91c305c92c748cd5170121',
    messagingSenderId: '22686388340',
    projectId: 'zen-challenge',
    storageBucket: 'zen-challenge.firebasestorage.app',
    iosBundleId: 'com.example.zenTsypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7HalGzA4vOUMHziaEACivubhToAIc74',
    appId: '1:22686388340:ios:91c305c92c748cd5170121',
    messagingSenderId: '22686388340',
    projectId: 'zen-challenge',
    storageBucket: 'zen-challenge.firebasestorage.app',
    iosBundleId: 'com.example.zenTsypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUYG5nG6lOPqzMlZkaRZgW2JJnER7CAsE',
    appId: '1:22686388340:web:1d9b09a39808d562170121',
    messagingSenderId: '22686388340',
    projectId: 'zen-challenge',
    authDomain: 'zen-challenge.firebaseapp.com',
    storageBucket: 'zen-challenge.firebasestorage.app',
    measurementId: 'G-XTWMGFVWD5',
  );

}