// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUW5j9umLSzbyTBUwVhuCQxSKuemdleI',
    appId: '1:714204708181:web:ee755c0ede3ea4d2ba83dc',
    messagingSenderId: '714204708181',
    projectId: 'zen-tsyp-app',
    authDomain: 'zen-tsyp-app.firebaseapp.com',
    storageBucket: 'zen-tsyp-app.firebasestorage.app',
    measurementId: 'G-SFPM743JP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bNs2IBcIjmKXfSYrnKfgNVQhq_gaysc',
    appId: '1:714204708181:android:5313b8151b4fed5cba83dc',
    messagingSenderId: '714204708181',
    projectId: 'zen-tsyp-app',
    storageBucket: 'zen-tsyp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmnDOYnpD74i6HJKLB0BggUHpnw-dmrE',
    appId: '1:714204708181:ios:ad8e3ee68ab73910ba83dc',
    messagingSenderId: '714204708181',
    projectId: 'zen-tsyp-app',
    storageBucket: 'zen-tsyp-app.firebasestorage.app',
    iosBundleId: 'com.example.zenTsypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmnDOYnpD74i6HJKLB0BggUHpnw-dmrE',
    appId: '1:714204708181:ios:ad8e3ee68ab73910ba83dc',
    messagingSenderId: '714204708181',
    projectId: 'zen-tsyp-app',
    storageBucket: 'zen-tsyp-app.firebasestorage.app',
    iosBundleId: 'com.example.zenTsypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDUW5j9umLSzbyTBUwVhuCQxSKuemdleI',
    appId: '1:714204708181:web:b52128993578a83aba83dc',
    messagingSenderId: '714204708181',
    projectId: 'zen-tsyp-app',
    authDomain: 'zen-tsyp-app.firebaseapp.com',
    storageBucket: 'zen-tsyp-app.firebasestorage.app',
    measurementId: 'G-87GQZ5E3VN',
  );

}